### ISSUE TITLE
The model tends to generate a lot of `<fim_pad>` tokens when using the FIM mode for generation.

### ISSUE THREAD

**Issue by Cucunnber** [QwenLM/Qwen2.5-Coder#101]
![image](https://github.com/user-attachments/assets/73ce81c4-3e09-4c60-af08-8766d2a62ee4)

**Comment by cyente** [comment]
you may need to add fim releated tokens into eos_tokens_ids

**Comment by cyente** [comment]
#99 similar issue

**Comment by Cucunnber** [comment]
I still enconter the same problem after modified config.json and generation_config.json with TGI-2.3.0

```shell
cat generation_config.json
{
  "bos_token_id": 151643,
  "eos_token_id": [
    151643,
    151662
  ],

  "max_new_tokens": 2048,
  "transformers_version": "4.45.0.dev0"
}
```

```shell
{
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "eos_token_id": [
    151643,
    151662
  ],
```
![image](https://github.com/user-attachments/assets/e67fa645-3a95-48e7-a388-87933f16e234)

**Comment by hcbr** [comment]
> I still enconter the same problem after modified config.json and generation_config.json with TGI-2.3.0
> 
> ```shell
> cat generation_config.json
> {
>   "bos_token_id": 151643,
>   "eos_token_id": [
>     151643,
>     151662
>   ],
> 
>   "max_new_tokens": 2048,
>   "transformers_version": "4.45.0.dev0"
> }
> ```
> 
> ```shell
> {
>   "architectures": [
>     "Qwen2ForCausalLM"
>   ],
>   "attention_dropout": 0.0,
>   "bos_token_id": 151643,
>   "eos_token_id": [
>     151643,
>     151662
>   ],
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/69720547/370255655-e67fa645-3a95-48e7-a388-87933f16e234.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyNDY5MzgsIm5iZiI6MTcyNzI0NjYzOCwicGF0aCI6Ii82OTcyMDU0Ny8zNzAyNTU2NTUtZTY3ZmE2NDUtM2E5NS00OGU3LWEzODgtODc5MzNmMTZlMjM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI1VDA2NDM1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4NmNmNTU2MjgyNmQ0MWM2ZjhlZjdmNzFjNmIxNWE5MzA0MDJlOGM3YjA4OTQ0YjE0MzY4ZTcwN2M3YWUwMGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0oXxwgoFWpO2HLsQdxwK8ybxKSafAhPNhfGvofmmY80)

I think you need to add "<|fim_pad|>" to special token.

**Comment by hcbr** [comment]
> ![image](https://private-user-images.githubusercontent.com/69720547/370149913-73ce81c4-3e09-4c60-af08-8766d2a62ee4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyNDcxNzQsIm5iZiI6MTcyNzI0Njg3NCwicGF0aCI6Ii82OTcyMDU0Ny8zNzAxNDk5MTMtNzNjZTgxYzQtM2UwOS00YzYwLWFmMDgtODc2NmQyYTYyZWU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI1VDA2NDc1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3MmM5M2ZiNDJlMjU0ZDA0ZGM4ZjQwNGI0MmVhNTMyYmNmMGJmYmYyMjk4OGUwMTVhYmNkZWQyMmE3MDI3ZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.BreS6lJ6OSZV2miv1GYjWDCD8j7TywjubHhqMsFBUBY)

![image](https://github.com/user-attachments/assets/e842c0bd-d181-4501-9b1d-6fb957239c31)
you can try like this.

**Comment by Cucunnber** [comment]
> > ![image](https://private-user-images.githubusercontent.com/69720547/370149913-73ce81c4-3e09-4c60-af08-8766d2a62ee4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyNDcxNzQsIm5iZiI6MTcyNzI0Njg3NCwicGF0aCI6Ii82OTcyMDU0Ny8zNzAxNDk5MTMtNzNjZTgxYzQtM2UwOS00YzYwLWFmMDgtODc2NmQyYTYyZWU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI1VDA2NDc1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3MmM5M2ZiNDJlMjU0ZDA0ZGM4ZjQwNGI0MmVhNTMyYmNmMGJmYmYyMjk4OGUwMTVhYmNkZWQyMmE3MDI3ZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.BreS6lJ6OSZV2miv1GYjWDCD8j7TywjubHhqMsFBUBY)
 you can try like this.

Thank you for your detailed response. However, my current requirement is to deploy server-side inference, and I have tried modifying the local model's config, but it hasn't worked.

**Comment by cyente** [comment]
This issue is being closed due to no response for more than 1 day.
