### ISSUE TITLE
在humaneval测试集中，vllm推理方式的通过率比transformer的低？

### ISSUE THREAD

**Issue by kartikzheng** [QwenLM/Qwen2.5-Coder#103]
你好，
1、请问在humaneval测试集中，vllm推理方式的通过率比transformer的推理方式差不多低10个百分点，这是正常的吗？是否有做过相关测试？
2、在python数据集中，transformer通过率也只有45%左右，其他语言通过率在70%-85%之间。是否有各个语言的评测结果供参考？
3、官方在humaneval数据集测试中推荐使用什么参数？
期待您们的回复，多谢

**Comment by cyente** [comment]
It is unexpected that there would be such a significant discrepancy in performance between vllm and transformers. Please carefully review your inference settings for any discrepancies;

Furthermore, we will gradually release all of our benchmarking scripts in the near future, so please stay tuned.

**Comment by kartikzheng** [comment]
> It is unexpected that there would be such a significant discrepancy in performance between vllm and transformers. Please carefully review your inference settings for any discrepancies;出乎意料的是，vllm 和 transformer 之间的性能会存在如此显着的差异。请仔细检查您的推理设置是否有任何差异;
> 
> Furthermore, we will gradually release all of our benchmarking scripts in the near future, so please stay tuned.此外，我们将在不久的将来逐步发布所有基准测试脚本，敬请期待。

感谢你的回复。请问你们是否有针对各个语言的具体评测结果供参考，谢谢。

**Comment by kartikzheng** [comment]
> > It is unexpected that there would be such a significant discrepancy in performance between vllm and transformers. Please carefully review your inference settings for any discrepancies;出乎意料的是，vllm 和 transformer 之间的性能会存在如此显着的差异。请仔细检查您的推理设置是否有任何差异;
> > Furthermore, we will gradually release all of our benchmarking scripts in the near future, so please stay tuned.此外，我们将在不久的将来逐步发布所有基准测试脚本，敬请期待。
> 
> 感谢你的回复。请问你们是否有Qwen2.5-Coder-7B-Instruct模型针对各个语言的具体评测结果供参考，谢谢。

可以的话，能否提供一下这个模型在vllm下的一些推荐配置什么的？

**Comment by cyente** [comment]
evaluations on  instruct model are on the way, please wait.

**Comment by cyente** [comment]
> evaluations on instruct model are on the way, please wait.

hey, the evaluations on instruct model have already released!

https://github.com/QwenLM/Qwen2.5-Coder/tree/main/qwencoder-eval/instruct

**Comment by kartikzheng** [comment]
> > evaluations on instruct model are on the way, please wait.
> 
> hey, the evaluations on instruct model have already released!
> 
> https://github.com/QwenLM/Qwen2.5-Coder/tree/main/qwencoder-eval/instruct

感谢分享，请问humaneval的数据集测试还没有开源？

**Comment by CSJianYang** [comment]
@kartikzheng Please refer to the multilingual verions of the humaneval (MultiPL-E)

https://github.com/QwenLM/Qwen2.5-Coder/tree/main/qwencoder-eval/instruct/multipl_e
