### ISSUE TITLE
为何我下载的模型问它是谁，他说OpenAI开发的助手？

### ISSUE THREAD

**Issue by 147591650** [QwenLM/Qwen2.5-Coder#110]
![微信截图_20240927144533](https://github.com/user-attachments/assets/191f4594-6228-4a9c-95fc-445ff9416b37)
我在这里下载找到的模型运行命令
![微信截图_20240927144558](https://github.com/user-attachments/assets/5a73d763-be82-4f80-93eb-21b5281f296a)
这是运行后问的问题！

**Comment by cyente** [comment]
We are currently reaching out to ollama to try and resolve the issue.
