### ISSUE TITLE
Qwen2.5-Coder data mixture ablation experiment eval benchmark

### ISSUE THREAD

**Issue by wentinghome** [QwenLM/Qwen2.5-Coder#119]
Hi, thanks for the great work!
I have a question for the eval benchmark.
In Table 3 of [Qwen2.5-Coder Technical Report](https://arxiv.org/pdf/2409.12186), what is the coding eval set Common BCB refer to? 
Also, confirm the base model for Table 3 experiment is QWen2.5-Coder 1.5B.
Thank you!

**Comment by cyente** [comment]
Thank you for your feedback. In this context, BCB refers to BigCodeBench. We will provide a detailed clarification shortly.
