### ISSUE TITLE
预训练fim数据切割问题

### ISSUE THREAD

**Issue by boshi950912** [QwenLM/Qwen2.5-Coder#122]
你好，请问fim任务的数据，代码的切割方式是随机切割的，还是加入了一个规则进行切割，比如说'\n' ':'等特殊的token。

**Comment by cyente** [comment]
You can refer to our technical report.

https://arxiv.org/abs/2409.12186

**Comment by shibo950912** [comment]
> You can refer to our technical report.
> 
> https://arxiv.org/abs/2409.12186

你好，我想问的是，fim_middle中间那段的前后位置怎么确定的，是随机选的嘛

**Comment by cyente** [comment]
The middle part refers to the blank section of the code scripts that requires completion.

**Comment by shibo950912** [comment]
> The middle part refers to the blank section of the code scripts that requires completion.

预训练构造fim数据的时候，fim_middle那一段前后位置怎么确定的，字符随机切割的嘛
