### ISSUE TITLE
7B-模型支持128K sequence length，但是config里面没有关于yarn的相关rope_type配置，还是用的是默认的 default？这个是为啥呀

### ISSUE THREAD

**Issue by Ericyfliu** [QwenLM/Qwen2.5-Coder#124]
{
--
  | "architectures": [
  | "Qwen2ForCausalLM"
  | ],
  | "attention_dropout": 0.0,
  | "bos_token_id": 151643,
  | "eos_token_id": 151643,
  | "hidden_act": "silu",
  | "hidden_size": 3584,
  | "initializer_range": 0.02,
  | "intermediate_size": 18944,
  | "max_position_embeddings": 32768,
  | "max_window_layers": 28,
  | "model_type": "qwen2",
  | "num_attention_heads": 28,
  | "num_hidden_layers": 28,
  | "num_key_value_heads": 4,
  | "rms_norm_eps": 1e-06,
  | "rope_theta": 1000000.0,
  | "sliding_window": 131072,
  | "tie_word_embeddings": false,
  | "torch_dtype": "bfloat16",
  | "transformers_version": "4.44.0",
  | "use_cache": true,
  | "use_sliding_window": false,
  | "vocab_size": 152064
  | }

**Comment by mofanke** [comment]
![image](https://github.com/user-attachments/assets/5d49fd46-feaa-427a-bc2d-d52e16803dbf)

**Comment by cyente** [comment]
> ![image](https://private-user-images.githubusercontent.com/54242816/375672608-5d49fd46-feaa-427a-bc2d-d52e16803dbf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MzU0MTcsIm5iZiI6MTcyODczNTExNywicGF0aCI6Ii81NDI0MjgxNi8zNzU2NzI2MDgtNWQ0OWZkNDYtZmVhYS00MjdhLWJjMmQtZDUyZTE2ODAzZGJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDEyMTE1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3OTVmMTgxYTdhMjBjZTQ1OTdlMmU4NjFiYWU2ZDBlOTZjYzNiMjQ1MGMzMGM2NTE1N2RkNDc3YTc1NjU5YTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.eyEhV3U6R4JKES43DWgX7rwi1Sf7BsNOd0WnrjNcTdw)


默认config没有开启yarn，你可以按照上面的配置方式来开启
