### ISSUE TITLE
继续预训练

### ISSUE THREAD

**Issue by boshi950912** [QwenLM/Qwen2.5-Coder#126]
你好，如果我想在qwen2.5-coder上面做继续预训练，该怎么做，有开源的预训练脚本嘛

**Comment by cyente** [comment]
You can consult the SFT scripts and modify them to align with your specific commands.

 https://github.com/QwenLM/Qwen2.5-Coder/tree/main/sft

**Comment by shibo950912** [comment]
> You can consult the SFT scripts and modify them to align with your specific commands.
> 
> https://github.com/QwenLM/Qwen2.5-Coder/tree/main/sft

你好，这个是做sft的环境。我这边是想做cpt，有参考的代码环境嘛

**Comment by cyente** [comment]
At present, we don't provide CPT scripts, however, you have the flexibility to adjust the SFT scripts to match your unique command requirements.
