### ISSUE TITLE
[AWQ BASE MODEL] Are there any plans to quantize Qwen2.5-Coder-7B base?

### ISSUE THREAD

**Issue by mofanke** [QwenLM/Qwen2.5-Coder#127]
Are there any plans to quantize Qwen2.5-Coder-7B base?
![image](https://github.com/user-attachments/assets/9690f115-c8ff-47cd-bcc6-5873387e2b60)

The current quantized versions are all instruct versions.

**Comment by cyente** [comment]
you may need to quantize base model by yourself. :)

**Comment by mofanke** [comment]
> you may need to quantize base model by yourself. :)

ok, I saw in the documentation that a calibrated dataset is needed. Do you have any suggestions for this? model will be used in code completion scenarios， thx

**Comment by cyente** [comment]
base model does not special desgined for any application scenarios. may be you need use some dataset that fit your scenarios. 

Looking forward to seeing you share your quantification practices on base models!
