### ISSUE TITLE
请问 Spider Text-to-SQL 数据集在 Qwen2.5-Coder 的训练集中吗？

### ISSUE THREAD

**Issue by ruilinWho** [QwenLM/Qwen2.5-Coder#132]
> 请问 Spider Text-to-SQL 数据集在 Qwen2.5-Coder 的训练集中吗？

我在 Spider 的训练集上进行测试 Qwen2.5-Coder，发现准确率非常高，想请问一下作者 Spider 的训练集/验证集是否参与了 Qwen2.5-Coder 的训练？

谢谢！

**Comment by shellhuang1227** [comment]
你是用spider数据集里的evaluation.py脚本还是test-suite-sql-eval里的evaluation.py脚本跑的评测呢？我是用的test-suite-sql-eval，这个一般比spider的低一些

**Comment by ruilinWho** [comment]
> 你是用spider数据集里的evaluation.py脚本还是test-suite-sql-eval里的evaluation.py脚本跑的评测呢？我是用的test-suite-sql-eval，这个一般比spider的低一些

我应该是和你用的同一个评测脚本（你说的后者），即 https://github.com/taoyds/test-suite-sql-eval。
我的命令是：
python3 evaluation.py \
--gold Gold.txt \
--pred Pred.txt \
--db {base_path}/test-suite-sql-eval/database/spider/database \
--etype all \
--table {base_path}/test-suite-sql-eval/database/spider/tables.json

**Comment by cyente** [comment]
hi guys, we only use the training set of spider.

**Comment by ruilinWho** [comment]
> hi guys, we only use the training set of spider.

好的，非常感谢！
