### ISSUE TITLE
请问官方是否有对Qwen2.5-Coder-7B-Instruct做过FIM相关数据集的评测？

### ISSUE THREAD

**Issue by kartikzheng** [QwenLM/Qwen2.5-Coder#134]
对Qwen2.5-Coder-7B-Instruct进行FIM santacoder数据集的评测，发现相比humaneval数据集评测，低了有10个百分点左右，特别是python语言，pass@1只有50%左右。而对比其他代码大模型，pass@1并没有明显的下滑。

**Comment by cyente** [comment]
Could you please provide us with the specific evaluation script and the prompts that have been tested? We will check  it out.

**Comment by cyente** [comment]
closed for no reply
