### ISSUE TITLE
32B model

### ISSUE THREAD

**Issue by caiduoduo12138** [QwenLM/Qwen2.5-Coder#135]
I am looking forward for the Qwen-coder-32B model

**Comment by Mushoz** [comment]
So are we all. Curious to see when they will release it.

**Comment by White-Friday** [comment]
关于32B的coder模型，有没有大概的发布时间

**Comment by Lamniaxyz** [comment]
I personally think, they are not going to release a 32B coder model. It's been over two months.

**Comment by cyente** [comment]
hi guys，32B has released along with 0.5B，3B，14B.  hoping to hear your feedback～
