### ISSUE TITLE
repo级别预训练数据构造

### ISSUE THREAD

**Issue by shibo950912** [QwenLM/Qwen2.5-Coder#140]
通义千问团队老师好：
repo级别数据构造时，假如有一个依赖库是获取不到的，比如是python本身的内置的库（eg：os）。那在prompt构造时，该怎么处理，file_content空着嘛，麻烦大佬解答。
<|repo_name|>{repo_name}
<|file_sep|>{file_path1}
{file_content1}
<|file_sep|>{file_path2}
{file_content2}
<|file_sep|>{file_path3} <|fim_prefix|>{code_pre}<|fim_suffix|>{code_suf}<|fim_middle|>{code_fim}<|endoftext|>

**Comment by cyente** [comment]
空着应该是可以的
