### ISSUE TITLE
技术报告里提到的Input-CoT和Output-CoT怎么理解？

### ISSUE THREAD

**Issue by chloefresh** [QwenLM/Qwen2.5-Coder#141]
不知道这样理解对不对？
Input-CoT：在输入的prompt里加入cot
out-CoT:在输出的回复里加入cot

**Comment by cyente** [comment]
No, you can refer to the evaluation explanation of cruxeval. https://crux-eval.github.io/

It means to evaluate cruxeval-input and cruxeval-output with cot.
