### ISSUE TITLE
Url endpoint for API Key of qwen (Alibabacloud)

### ISSUE THREAD

**Issue by erik445445** [QwenLM/Qwen2.5-Coder#145]
Hello guys, sorry maybe is not the right place or section to make this question but maybe some of you knows how to address this issue. Im using a chat client that can log many api ai services models with API Key and endpoint url. I did an Alibaba Cloud services account and I got an API Key, I want to use qwen-max, but im struggling with the endpoint access, every url I try is not good, 

im using this 

https://dashscope.aliyuncs.com/compatible-mode/v1/

https://dashscope-intl.aliyuncs.com/api/v1

but none of them works. Someone know the right url to use? thanks.

**Comment by cyente** [comment]
hi,  you may refer to this pages. there are two different ways to use the api.

https://help.aliyun.com/zh/model-studio/developer-reference/use-qwen-by-calling-api?disableWebsiteRedirect=true#a9b7b197e2q2v

Or you can call directly, consult the customer service of aliyun, they should help you solve the problem.
