### ISSUE TITLE
Default temperature 

### ISSUE THREAD

**Issue by ssk705** [QwenLM/Qwen2.5-Coder#146]
CodeQwen1.5-7B-Chat . What's the default temperature of this model?

**Comment by cyente** [comment]
We haven't yet conducted thoroughly comprehensive testing on inference strategies. You can simply use  a general default setting , we encourage you to try more different settings. Hoping to see your feedback!
```
  "temperature": 0.7,
  "top_p": 0.8,
  "repetition_penalty": 1.05,
```

**Comment by SmartManoj** [comment]
> "temperature": 0.7,

Shouldn't the `temperature` be 0 for coding?
