### ISSUE TITLE
How synthetic data were generated?

### ISSUE THREAD

**Issue by wasiahmad** [QwenLM/Qwen2.5-Coder#147]
Hello,

In the technical report, it was mentioned that CodeQwen1.5 was used to generate synthetic data, but there is no further detail. Is it possible to elaborate? For example, what kind of technique is being used for synthetic data generation?

I found this [tweet](https://x.com/rohanpaul_ai/status/1837982057693131055?lang=en) that shares some detail. Is it correct? If yes, what are those code snippets which are involved in instruction generation?

**Comment by huybery** [comment]
Some details can be found in the technical report: https://arxiv.org/abs/2409.12186
