### ISSUE TITLE
Qwen2.5-Coder-7B-Instruct 的 BenchMark 结果

### ISSUE THREAD

**Issue by FearfulTomcat27** [QwenLM/Qwen2.5-Coder#155]
在我所查阅的本仓库内容中，未能寻获Qwen2.5-Coder-7B-Instruct针对MultiPL-E在每种语言上的具体评估结果，这让我感到有些困惑。因此，我希望能就此事向您提出询问，并恳请指导是否存在可用于评估MultiPL-E的脚本或相关工具。

**Comment by huybery** [comment]
https://github.com/QwenLM/Qwen2.5-Coder/tree/main/qwencoder-eval/instruct/multipl_e

Specific results are in the paper: https://arxiv.org/abs/2409.12186
