### ISSUE TITLE
Cursor edit + Qwen2.5-Coder prompt?

### ISSUE THREAD

**Issue by Owen-Qin** [QwenLM/Qwen2.5-Coder#156]
Thanks for your great work!

The demonstrated result of Qwen2.5-Coder + Cursor looks amazing (https://qwenlm.github.io/zh/blog/qwen2.5-coder-family/#qwen25-coder--cursor). 

I'd like to know which model (instruct or base? the model size?) did you use for the inline edit use case. Could you share the prompt as well?

**Comment by cyente** [comment]
The easiest way to deploy our model is to use dashscope with `qwen-coder-plus'  model, and complete the endpoint, model names  and the ak in it. You can try ``Qwen2.5-Coder + Cursor'' on your own.

**Comment by cyente** [comment]
#159
