### ISSUE TITLE
希望跟上o1的步伐, 达到强逻辑推理的层次.

### ISSUE THREAD

**Issue by qwas982** [QwenLM/Qwen2.5-Coder#158]
AI程序员的基础应该是像o1那样的强逻辑推理,   
现在的代码生成大模型, 只能写**很短**的代码, 还很多时候理解不到位, 也无法在多个文件里的上下文进行增删改查.   
什么时候出产一个在给出`目录`与`提纲`的情况下, 就能自动生成多文件的大项目, 1万行起步的多模块项目.   
能访问系统IO, 能访问文件系统, 把强逻辑推理应用到多模态, 让AI程序员可以自己看屏幕, 用视觉逻辑推理去理解应该怎么操纵电脑(像克劳德3.5一样)在IDE(或文本编辑器)里写代码.

**Comment by cyente** [comment]
感谢您的反馈。qwen2.5-coder包含了长上下文多文件的增删改查的能力，但依旧存在很大的提升空间。我们会持续努力突破。

**Comment by huybery** [comment]
on the way.

**Comment by qwas982** [comment]
[**AI程序员**]需要在网页版的最左边选项卡专门做一个按钮进入.   
界面设计: 可以集成一个网页版的VSC样式, 分三栏; `一个目录栏`, `一个编辑区栏`, `一个聊chat栏`, 大模型可以访问三者.   
大模型可以做一个`内存数据库`, 用来存储三者的上下文, 通过`记住`三者的`关系`用以实现自由`跳转`. 这样就不需要增加多个大模型在每步只做一件事, 用一个大模型做全部事, 降低计算量, 提升速度, 降低成本.
第二, 可以在聊chat栏, 增加一个`子栏`, 用`图形块` + `连线`的方式配合`聊`模式, 向大模型表明用户的意图, 抽象自[`UML + comfyUI + UE5蓝图编程`]这类使用方式. 大模型不需要一次生成一个项目的全部代码, 通过在内存数据库里记住"一个项目的多个文件, 与编辑区栏, 与来自用户的随时中断"这些上下文, 大模型进行逻辑推理后, 再生成. 需要设计一个中间件指挥大模型操作.
