### ISSUE TITLE
How can I use Qwen2.5-Coder 32B in Cursor?

### ISSUE THREAD

**Issue by IamTirion** [QwenLM/Qwen2.5-Coder#159]
https://qwenlm.github.io/zh/blog/qwen2.5-coder-family/#qwen25-coder--cursor

As shown here. May I ask how Qwen2.5-Coder 32B be used in Cursor? I do not see it in the models list.

**Comment by cyente** [comment]
Hi, your can deploy Qwen2.5-Coder-32B-instruct in openai api format.

For example, you can try aliyun product, ``dashscope'',  check it out here https://help.aliyun.com/zh/model-studio/user-guide/qwen-coder?spm=a2c4g.11186623.0.0.ce3c4823oIqYUF .

step 1: regist aliyun account and activate daschope get the DASHSCOPE_API_KEY;

step2:  open the ``Preferences>Cursor Settings''

step3:  add model name you want to used such as qwen-coder-plus,  qwen2.5-coder-32b-instruct, choose one from here https://help.aliyun.com/zh/model-studio/user-guide/qwen-coder?spm=a2c4g.11186623.0.0.ce3c4823oIqYUF.

step4: Override openai base url with dashscope's  compatible mode  with openai api, ``https://dashscope.aliyuncs.com/compatible-mode/v1''.

step5: fill your  DASHSCOPE_API_KEY in openai api key.

![image](https://github.com/user-attachments/assets/116ca875-5178-455a-aa41-56a71fb0f9da)

**Comment by IamTirion** [comment]
Thank you.
