### ISSUE TITLE
The generated code has a special mark. <|endoftext|>   <|cursor|>

### ISSUE THREAD

**Issue by gaomeng20241028** [QwenLM/Qwen2.5-Coder#161]
I use the following template：

prompt_template = "<|fim_prefix|>{prefix}<|fim_suffix|>{suffix}<|fim_middle|>"

**Comment by cyente** [comment]
you could simply remove the " <|cursor|>" and end the outputs  at  the "<|endoftext|>" .

By the way, which model you are using?

**Comment by gaomeng20241028** [comment]
> you could simply remove the " <|cursor|>" and end the outputs at the "<|endoftext|>" .
> 
> By the way, which model you are using? and could you give as an example of this bad case?

this one, qwen2.5-coder:32b-instruct-q8_0.   I use the code completion tool tabby to access the model, and the content of code completion includes " <|cursor|>" and  "<|endoftext|>"

**Comment by gaomeng20241028** [comment]
![微信图片_20241114101159](https://github.com/user-attachments/assets/e21150f5-df71-4cf1-9219-dde70ff53a10)

**Comment by cyente** [comment]
> > you could simply remove the " <|cursor|>" and end the outputs at the "<|endoftext|>" .
> > By the way, which model you are using? and could you give as an example of this bad case?
> 
> this one, qwen2.5-coder:32b-instruct-q8_0. I use the code completion tool tabby to access the model, and the content of code completion includes " <|cursor|>" and "<|endoftext|>"

we suggest you to use base model not the instruct model for code completion.

**Comment by cyente** [comment]
> ![微信图片_20241114101159](https://private-user-images.githubusercontent.com/175574123/386015121-e21150f5-df71-4cf1-9219-dde70ff53a10.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1ODk2MDAsIm5iZiI6MTczMTU4OTMwMCwicGF0aCI6Ii8xNzU1NzQxMjMvMzg2MDE1MTIxLWUyMTE1MGY1LWRmNzEtNGNmMS05MjE5LWRkZTcwZmY1M2ExMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNFQxMzAxNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMmQ2YWQyMjY5NDcyMTkwNGVlZjk4ODYyZWZlYjg3NTcwMzdlZWNkNzUyNzUyNzRhNDJhZTE0MWU0MzFjNjkwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.HyXWpgoPNkvWTepe2qDg-h2B3EwJp_4RJ7lgXcdPVMA)

Where is your input text located in the picture? and where is the output?

**Comment by gaomeng20241028** [comment]
> > ![微信图片_20241114101159](https://private-user-images.githubusercontent.com/175574123/386015121-e21150f5-df71-4cf1-9219-dde70ff53a10.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1ODk2MDAsIm5iZiI6MTczMTU4OTMwMCwicGF0aCI6Ii8xNzU1NzQxMjMvMzg2MDE1MTIxLWUyMTE1MGY1LWRmNzEtNGNmMS05MjE5LWRkZTcwZmY1M2ExMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNFQxMzAxNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMmQ2YWQyMjY5NDcyMTkwNGVlZjk4ODYyZWZlYjg3NTcwMzdlZWNkNzUyNzUyNzRhNDJhZTE0MWU0MzFjNjkwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.HyXWpgoPNkvWTepe2qDg-h2B3EwJp_4RJ7lgXcdPVMA)
> 
> Where is your input text located in the picture? and where is the output?

Only output is shown here. Input is a comment. Write a quick line.

**Comment by gaomeng20241028** [comment]
![Uploading 微信图片_20241115135438.png…]()

**Comment by cyente** [comment]
show me the input, there may be something wrong. it's a weired output

**Comment by gaomeng20241028** [comment]
I use the following template：

prompt_template = "<|fim_prefix|>{prefix}<|fim_suffix|>{suffix}<|fim_middle|>"

**Comment by cyente** [comment]
Could you please provide detailed information to help us reproduce the issue? I've tried many times but still haven't been able to replicate it. orz...

**Comment by cyente** [comment]
Due to the lack of response for a long time, this issue has been temporarily closed.
