### ISSUE TITLE
 max_new_token max value for Qwen2.5-Coder Instruct?

### ISSUE THREAD

**Issue by Thireus** [QwenLM/Qwen2.5-Coder#165]
It is there for Qwen2.5: https://huggingface.co/Qwen/Qwen2.5-72B-Instruct mentions "Context Length: Full 131,072 tokens and generation 8192 tokens", so 8K.

But not for Qwen2.5-Coder…

https://huggingface.co/Qwen/Qwen2.5-Coder-32B-Instruct only mentions "Context Length: Full 131,072 tokens" and nothing about how many tokens max it can produce.

I cannot find the info anywhere… what is the max value of max_new_token for the Qwen2.5-Coder Instruct releases?

**Comment by cyente** [comment]
when you use yarn,  you should limit the sum of input and output with in 131072 tokens. 

We advise against generating overly long outputs, but you can test it in your scenarios.

**Comment by Thireus** [comment]
Thank you. And when yarn is not used, what is the max output?

**Comment by cyente** [comment]
when yarn is not used, you should limit the sum of input and output with in 32k tokens.

also, we advise against generating overly long outputs, but you can try for long generation.
