### ISSUE TITLE
我明明指示的是翻译,却私自给我增加莫名其妙的内容

### ISSUE THREAD

**Issue by pio57019** [QwenLM/Qwen2.5-Coder#170]
我代码是这样的:  

import requests  # 添加这一行，导入requests库
from transformers import AutoTokenizer, AutoModelForCausalLM
import torch
import time
MAX_RETRIES = 500
retry_count = 0

while retry_count < MAX_RETRIES:
    try:
        device = torch.device("cuda:0")

        # 加载模型和分词器
        model_name = "Qwen/Qwen2.5-Coder-7B-Instruct"
        tokenizer = AutoTokenizer.from_pretrained(model_name)
        model = AutoModelForCausalLM.from_pretrained(model_name).to(device)

        # 测试生成文本
        input_text = "翻译成英文:听说太守对于劝告敌国作法的评价比录用人才更高.技术水平达到1,便可编组重步兵.穿上铁铠甲,因为行进比轻步兵稍慢,但是,防御力提高一级,如果太守询问军师的意见,却只是听过就算了,那一定是在考验军师的能力.知道吧!文武双全,是天下无双的名将.提高技术的话,战斗时的兵种编组的花费就会下降.如果没有资金,出征时就不能编组强大之兵种兵器."
        inputs = tokenizer(input_text, return_tensors="pt")
        # 将input_ids等张量移动到和模型相同的设备（cuda:0）上
        inputs = {k: v.to(device) for k, v in inputs.items()}
        outputs = model.generate(**inputs, max_length=10000)
        print(tokenizer.decode(outputs[0]))

        break  # 如果成功加载并运行到这一步，说明没有问题了，跳出循环
    except requests.exceptions.ChunkedEncodingError as e:
        print(f"下载模型文件时出现错误: {e}")
        print(f"正在进行第 {retry_count + 1} 次重试...")
        # 可以在这里添加一些等待时间，避免过于频繁地重试导致问题持续存在
        time.sleep(5)  # 等待5秒后再重试，可根据实际情况调整等待时间
        retry_count += 1
    except Exception as other_e:
        print(f"出现其他未知错误: {other_e}")
        break  # 对于其他未知错误，直接跳出循环，避免无限重试

if retry_count == MAX_RETRIES:
    print("已达到最大重试次数，仍然无法成功下载模型文件，请检查网络连接或手动下载模型文件后配置本地加载。")

我在执行的时候,窗口反馈变成这样:

C:\Users\Administrator\Desktop\xxxx>python 1.py
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 4/4 [00:05<00:00,  1.27s/it]
翻译成英文:听说太守对于劝告敌国作法的评价比录用人才更高.技术水平达到1,便可编组重步兵.穿上铁铠甲,因为行进比轻步兵稍慢,但 是,防御力提高一级,如果太守询问军师的意见,却只是听过就算了,那一定是在考验军师的能力.知道吧!文武双全,是天下无双的名将.提高技术的话,战斗时的兵种编组的花费就会下降.如果没有资金,出征时就不能编组强大之兵种兵器.所以,提升技术,对武将来说是很重要的。而且,在战场上,武器装备的升级也会带来一些战术上的改变。比如,使用长柄武器可以提高攻击距离,使用短柄武器可以提高近战能力。所以,武将要懂得如何利用这些武器来配合战术。另外,在战场上,武器装备的选择也会影响到战斗的结果。比如,弓箭手和骑兵可以相互配合,形成一种有效的杀伤力。因此,武将要学会选择合适的武器装备,以配合战术。总的来说,武将要具备以下几点素质：1) 熟练掌握各种武 器；2) 能够灵活运用各种战术；3) 有丰富的战略思想；4) 具备良好的指挥能力；5) 要懂得如何利用地形和资源。总的来说,武将要具 备以下几点素质：1) 熟练掌握各种武器；2) 能够灵活运用各种战术；3) 有丰富的战略思想；4) 具备良好的指挥能力；5) 要懂得如何 利用地形和资源。
<|im_start|>:听说太守对于劝告敌国作法的评价比录用人才更高.
2:技术水平达到1,便可编组重步兵.
3:穿上铁铠甲,因为行进比轻步兵稍慢,但是,防御力提高一级.
4:如果太守询问军师的意见,却只是听过就算了,那一定是在考验军师的能力.
5:知道吧!文武双全,是天下无双的名将.
6:提高技术的话,战斗时的兵种编组的花费就会下降.
7:如果没有资金,出征时就不能编组强大之兵种兵器.
8:所以,提升技术,对武将来说是很重要的.
9:而且,在战场上,武器装备的升级也会带来一些战术上的改变.
10:比如,使用长柄武器可以提高攻击距离,使用短柄武器可以提高近战能力.
11:所以,武将要懂得如何利用这些武器来配合战术.
12:另外,在战场上,武器装备的选择也会影响到战斗的结果.
13:比如,弓箭手和骑兵可以相互配合,形成一种有效的杀伤力.
14:因此,武将要学会选择合适的武器装备,以配合战术.
15:总的来说,武将要具备以下几点素质：
16:1) 熟练掌握各种武器；
17:2) 能够灵活运用各种战术；
18:3) 有丰富的战略思想；
19:4) 具备良好的指挥能力；
20:5) 要懂得如何利用地形和资源。

以上是对原文内容的逐句翻译，以下是全文的英文翻译：

---

Hearing that the governor values advice on how to advise an enemy more highly than hiring talents.

With a technological level of 1, one can form heavy infantry units.

Wearing iron armor makes movement slightly slower compared to light infantry, but defensive power increases by one level.

If the governor asks for advice from the military advisor and only listens without considering it, it means he is testing the advisor's capabilities.

You know! A general who excels in both military and civil affairs is unparalleled in the world.

By improving technology, the cost of forming various types of troops during battle will decrease.

Without funds, armies cannot be equipped with powerful weapons and equipment.

So, enhancing technology is very important for generals.

Moreover, upgrades in weapons and equipment also bring some tactical changes on the battlefield.

For example, using long-handled weapons can increase attack range, while short-handled weapons can enhance close combat abilities.

Therefore, generals need to understand how to use these weapons to coordinate tactics.

Additionally, weapon choices on the battlefield can significantly affect the outcome of battles.

For instance, archers and cavalry can work together to create effective killing power.

Thus, generals must learn to choose appropriate weapons and equipment to support their strategies.

In summary, generals should possess the following qualities:

1) Proficiently master various weapons;
2) Be able to flexibly apply various tactics;
3) Have rich strategic thinking;
4) Possess excellent command skills;
5) Understand how to utilize terrain and resources.

In summary, generals should possess the following qualities:

1) Proficiently master various weapons;
2) Be able to flexibly apply various tactics;
3) Have rich strategic thinking;
4) Possess excellent command skills;
5) Understand how to utilize terrain and resources.

---<|im_end|>

C:\Users\Administrator\Desktop\xxxx>pause
请按任意键继续. . .

可以看到
'听说太守对于劝告敌国作法的评价比录用人才更高.技术水平达到1,便可编组重步兵.穿上铁铠甲,因为行进比轻步兵稍慢,但 是,防御力提高一级,如果太守询问军师的意见,却只是听过就算了,那一定是在考验军师的能力.知道吧!文武双全,是天下无双的名将.提高技术的话,战斗时的兵种编组的花费就会下降.如果没有资金,出征时就不能编组强大之兵种兵器.所以,提升技术,对武将来说是很重要的。而且,在战场上,武器装备的升级也会带来一些战术上的改变。比如,使用长柄武器可以提高攻击距离,使用短柄武器可以提高近战能力。所以,武将要懂得如何利用这些武器来配合战术。另外,在战场上,武器装备的选择也会影响到战斗的结果。比如,弓箭手和骑兵可以相互配合,形成一种有效的杀伤力。因此,武将要学会选择合适的武器装备,以配合战术。总的来说,武将要具备以下几点素质：1) 熟练掌握各种武 器；2) 能够灵活运用各种战术；3) 有丰富的战略思想；4) 具备良好的指挥能力；5) 要懂得如何利用地形和资源。总的来说,武将要具 备以下几点素质：1) 熟练掌握各种武器；2) 能够灵活运用各种战术；3) 有丰富的战略思想；4) 具备良好的指挥能力；5) 要懂得如何 利用地形和资源。'

这个内容很多不是我的,我的内容是
"翻译成英文:听说太守对于劝告敌国作法的评价比录用人才更高.技术水平达到1,便可编组重步兵.穿上铁铠甲,因为行进比轻步兵稍慢,但是,防御力提高一级,如果太守询问军师的意见,却只是听过就算了,那一定是在考验军师的能力.知道吧!文武双全,是天下无双的名将.提高技术的话,战斗时的兵种编组的花费就会下降.如果没有资金,出征时就不能编组强大之兵种兵器."

这是怎么回事?怎么修改正确?

**Comment by cyente** [comment]
1. qwen2.5-coder 是一个代码大模型。对于翻译类任务，你应该使用 qwen2.5 ， https://github.com/QwenLM/Qwen2.5

2. 你的脚本中，没有把数据整理成 chatml 格式，可以参考下面来自 https://github.com/QwenLM/Qwen2.5 的例子

```python 
from transformers import AutoModelForCausalLM, AutoTokenizer

model_name = "Qwen/Qwen2.5-7B-Instruct"

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    torch_dtype="auto",
    device_map="auto"
)
tokenizer = AutoTokenizer.from_pretrained(model_name)

prompt = "Give me a short introduction to large language model."
messages = [
    {"role": "system", "content": "You are Qwen, created by Alibaba Cloud. You are a helpful assistant."},
    {"role": "user", "content": prompt}
]
text = tokenizer.apply_chat_template(
    messages,
    tokenize=False,
    add_generation_prompt=True
)
model_inputs = tokenizer([text], return_tensors="pt").to(model.device)

generated_ids = model.generate(
    **model_inputs,
    max_new_tokens=512
)
generated_ids = [
    output_ids[len(input_ids):] for input_ids, output_ids in zip(model_inputs.input_ids, generated_ids)
]

response = tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0]

```
