### ISSUE TITLE
Error in evaluation on Qwen2.5-Coder

### ISSUE THREAD

**Issue by Zephyreeze** [QwenLM/Qwen2.5-Coder#172]
When run 'bash run_evaluate_cq2.5.sh' to evaluate HumanEval and MBPP, there is an error this line:"from evalplus.data import get_human_eval_plus"(line24 in generation.py). It seems that "data" does not exist in evalplus?

**Comment by cyente** [comment]
Please provide us with more detailed information, including the log and the environment.

**Comment by Zephyreeze** [comment]
The environment is configured as described in the README file. However, after running ‘bash run_evaluate_cq2.5.sh’, I encountered the following issue:
