### ISSUE TITLE
tokenizer.json changed after ms-swift sft

### ISSUE THREAD

**Issue by oasis-0927** [QwenLM/Qwen2.5-Coder#176]
First of all, thanks for this great work !
I'm using ms-swift(2.6.0.post1) and transformers(4.46.3) to  LORA-finetune the qwen-2.5-coder-32B model.  
The SFT and export process was processed fine but when I try to load the LORA-merged model, the tokenizer will raise "Data did not match any variant of untagged enum" error. 
I looked into the merged tokenizer.json  file and I found out that the format of "merges" part was changed as follows:
Before SFT:
![image](https://github.com/user-attachments/assets/19409b09-234e-4d8d-a13e-7186003026fb)

After SFT:
![image](https://github.com/user-attachments/assets/48db4e01-712a-455e-a64e-b70e0f7a526b)

Here are some discussions that may help.
https://github.com/huggingface/transformers/issues/30324
https://github.com/unslothai/unsloth/issues/1059

**Comment by cyente** [comment]
hi, you may need to attach this issue to ms-swift.

**Comment by oasis-0927** [comment]
> hi, you may need to attach this issue to ms-swift.

Got it.
