### ISSUE TITLE
the chat template `qwen2_5` corresponding to the model `qwen2_5-coder-32b-instruct-awq` is in chat format. Please use the `chat.completions` API. 

### ISSUE THREAD

**Issue by gitYuZui** [QwenLM/Qwen2.5-Coder#178]
# 部署方式
ms-swift + vllm 方式部署

# 错误说明：
我从/v1/chat/completions的方式调用进来是正常的。但是从 /v1/completions方式调用，接口会报错：the chat template `qwen2_5` corresponding to the model `qwen2_5-coder-32b-instruct-awq` is in chat format. Please use the `chat.completions` API. 
![image](https://github.com/user-attachments/assets/85a2a714-8e1e-4d48-a826-9c48d4fabaee)
![image](https://github.com/user-attachments/assets/9b892fd7-5c0d-41c4-869a-3ea8c3ee2792)

# 问题：
1、这是因为这个模型不支持completions方式调用吗？
2、如何解决？
3、有没有更好的方式去适配 continue插件？

**Comment by cyente** [comment]
please give us some time to check it out

**Comment by cyente** [comment]
Hi, the completions format is still under development. Please check back in a few days and stay tuned for MS-swift announcement
