### ISSUE TITLE
 I deploy a model using vLLM, I found that in the benchmark, INT8 > BF16?

### ISSUE THREAD

**Issue by endNone** [QwenLM/Qwen2.5-Coder#179]
I deployed the BF16 and INT8 versions of Qwen2.5-coder-32b-instruct using vLLM (version 0.6.1) and evaluated them with OpenCompass. Surprisingly, BF16 underperformed compared to INT8 on several metrics. For example, on HumanEval's pass@1:

HumanEval pass@1 (single inference):

BF16: 87.80
INT8: 88.41
AWQ: 86.59

**Comment by endNone** [comment]
![image](https://github.com/user-attachments/assets/707fd2c1-1e83-473b-92dd-948d21e7d9e0)

I asked in a WeChat group and found that others have encountered similar situations.

**Comment by cyente** [comment]
First of all, thank you for sharing your experimental results with us!

The inevitable consequence of quantization is some performance loss.  
INT8 model has a comparable performance on humaneval indicates that our quantitative strategy is successful. 

HumaEval is a relatively volatile metric, and a fluctuation of around 1 point might be normal for a single model.

**Comment by cyente** [comment]
It is humaneval pass@1.

You can reproduce the evaluation of Humaneval using the script provided [here](https://github.com/QwenLM/Qwen2.5-Coder/tree/main/qwencoder-eval/instruct/multipl_e).
