### ISSUE TITLE
Base model weirdly generates a special mark of "<|cursor|>" .

### ISSUE THREAD

**Issue by umutberhan94** [QwenLM/Qwen2.5-Coder#193]
I use 1.5b base model with `<|fim_prefix|>${prefixCode}<|fim_suffix|>${suffixCode}<|fim_middle|>` prompt and it sometimes generates <|cursor|> mark in the output. 

Here is what happens after typing "const".
![{BB0E1819-D075-458D-A95A-CB83E600099F}](https://github.com/user-attachments/assets/e568d067-9221-41ee-b595-63ad4d4609f3)

**Comment by cyente** [comment]
Thank you for your feedback! you could simply replace the <|cursor|>  by post-process.

**Comment by umutberhan94** [comment]
> Thank you for your feedback! you could simply replace the <|cursor|> by post-process.

Will do, I just wanted to let you know. Thank you guys for this well-trained model.

**Comment by umutberhan94** [comment]
> Thank you for your feedback! you could simply replace the <|cursor|> by post-process.

Will do! I just wanted to inform you about this behavior. Thank you for providing such a well-trained model.
