### ISSUE TITLE
adding documents (docx, md, pdf) into qwen2.5-coder

### ISSUE THREAD

**Issue by ozgecinko** [QwenLM/Qwen2.5-Coder#203]
hi! 👋🏻 I've been exploring Qwen2.5-Coder, is it possible to add documents such as docx, pdf or markdown directly into the model for processing?

**Comment by cyente** [comment]
markdown is ok, i am not sure what your mean by directly adding docx or pdf. 

If you mean directly inputting content as binary files into the model, that's probably not a good idea. Usually, these types of files should rely on a tool that parses them into regular text.

**Comment by ozgecinko** [comment]
thanks for your response, this answers my question.
I was wondering if qwen2.5-coder could work in a way where I could provide new knowledge using docx files.
thx again for your help, closing this issue now.
