### ISSUE TITLE
How to train model with Lora?

### ISSUE THREAD

**Issue by Zongru-Wang** [QwenLM/Qwen2.5-Coder#217]
Hello, 
How to train this model using Lora? 
I saw examples in https://github.com/QwenLM/Qwen/blob/main/finetune.py,
But I didn't find this --use_lora \ option available in Qwen-coder? 

Do you have any suggestion?

**Comment by CSJianYang** [comment]
Currently, the script only supports the sft training with full parameters. We will try to support the training with LoRA.
