### ISSUE TITLE
Has Qwen2.5-Coder-Instruct been trained on bird-dev?

### ISSUE THREAD

**Issue by LJHzju** [QwenLM/Qwen2.5-Coder#223]
Hello, I would like to know whether the experimental results of Qwen2.5-Coder-7B-Instruct in the technical report on Bird were tested on bird-dev or bird-test. 

Besides, has the Qwen2.5-Coder-7B-Instruct model ever been used for SFT with the data in bird-dev.json?

**Comment by huybery** [comment]
Qwen2.5-Coder-7B-Instruct was evaluated on bird-dev, and bird-dev was not used during SFT.

**Comment by LJHzju** [comment]
But I have observed that almost all models have lower perplexity on bird-dev than on bird-train. Have special treatments been applied to bird-dev?
