### ISSUE TITLE
Where is the code for long-context evaluation of base model?

### ISSUE THREAD

**Issue by canghongjian** [QwenLM/Qwen2.5-Coder#97]
Great work and thanks for your detailed description!
From your paper, you use a task named "Needle in the Code" to evaluate the long-context capability of base model, but I can not find where it is in this repo.
Could you please share more details about it or provide more experiments details such as the prompt or generation config?

Thanks a lot.

**Comment by cyente** [comment]
The evaluation code is undergoing an update and will be available shortly. Thank you for your patience.

**Comment by Bourhano** [comment]
Hello @cyente, what is the status for the "Needle in the Code" evaluation scripts? Is it still going to be published?
