### ISSUE TITLE
Model evaluation results reported in paper/blog

### ISSUE THREAD

**Issue by ll-antn** [QwenLM/Qwen2.5-Coder#98]
In your blog and paper you reported results which show **88.4** score of 7B instruction tuned model on **HumanEval** benchmark. However  `evaluation/eval_plus/released/results/humaneval/codeqwen_chat.txt `shows only **0.835**, and exact same number I get when running evaluation locally. Could you please elaborate on that and help me reproduce the reported numbers?

**Comment by cyente** [comment]
hi， the  result file in `codeqwen_chat.txt` is still the old version of codeqwen1.5, you may also use the wrong model?
