### ISSUE TITLE
Why special tokens such as <|fim_prefix|>、<|fim_pad|> in generated text ?

### ISSUE THREAD

**Issue by hcbr** [QwenLM/Qwen2.5-Coder#99]
When i use Code Completion (Fill in the middle), sometimes, special tokens such as <|fim_prefix|>、<|fim_pad|> may appear in generated text.
Input:
![image](https://github.com/user-attachments/assets/cf2b80b2-91ff-46bc-be00-244b9db799fe)
generated text:
![image](https://github.com/user-attachments/assets/be10a920-47f6-408c-a890-e776a7284802)

even,the generated text can be:
![image](https://github.com/user-attachments/assets/89325f1e-7905-4a2c-be2b-ce39399be547)

Did I overlook something while using it？

**Comment by ljy805** [comment]
qwen2.5相对于qwen1.5的fim tokens变了，你这个是1.5的fim tokens吧

**Comment by asmeurer** [comment]
I think you need to add `<|file_sep|>` as a stop token. Most base models have several possible stop tokens that they might output when doing FIM.

**Comment by hcbr** [comment]
> I think you need to add `<|file_sep|>` as a stop token. Most base models have several possible stop tokens that they might output when doing FIM.

Thank you for your suggestion. I have now added the fim related tokens to the eos_token id list
